# Generated by Django 3.2 on 2023-06-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('endroit', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'Capteur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temp', models.FloatField(null=True)),
                ('id_capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSAE.capteur')),
            ],
            options={
                'db_table': 'Description',
                'managed': True,
            },
        ),
    ]
