# Generated by Django 3.2 on 2023-06-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSAE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteur',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'managed': False},
        ),
    ]
