# Generated by Django 3.2 on 2023-06-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSAE', '0002_auto_20230622_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteur',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'managed': True},
        ),
    ]
