# Generated by Django 3.2 on 2023-06-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSAE', '0003_auto_20230622_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='endroit',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
