# Generated by Django 4.2.2 on 2023-06-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSAE', '0004_description_endroit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capteur',
            table='capteur',
        ),
        migrations.AlterModelTable(
            name='description',
            table='description',
        ),
    ]
